version: 2.1

jobs:
  test:
    machine: true
    steps:
      - checkout
      - run:
          name: Run Jest Tests
          command: |
            cd ./service
            npm install
            npm test
            
  deploy:
    docker:
      - image: arvindr226/alpine-ssh
    steps:
      - checkout
      - run: ssh -oStrictHostKeyChecking=no -v $USER@$IP "~/SendASnack/Service/Frontend/deploy.sh"
          
workflows:
  build-and-test:
    jobs:
      - test
      - deploy:
          requires:
            - test
          filters:
            branches:
              only:
                - develop
                - master
